package com.example.demo.constant;

public enum CommonMessage {

    SUCCESS(0, "Thành công"),
    FAILED(-1, "Không thành công"),
    VERSION_INVALID(-1, "Version không hợp lệ"),
    TOKEN_INVALID(-1, "Token không hợp lệ"),
    PATH_ID_INVALID(-1, "ID không hợp lệ"),
    UPDATE(0, "Cập nhật thành công"),
    UPDATE_ORD_VOTING_SUCCESS(0,"Cập nhật Biểu quyết thành công."),
    CANT_DELETE_BC_OF_DATA_BINDING(-1,"Không thể xóa {} vì ràng buộc dữ liệu"),
    DELETE_OBJ_SUCCESS(0, "Xoá {} thành công"),
    LOCK_OBJ_SUCCESS(0, "Khoá {} thành công"),
    UNLOCK_OBJ_SUCCESS(0, "Mở khoá {} thành công"),
    RESET_PASSWORD_SUCCESS(0, "Reset mật khẩu thành công"),
    CREATE_USER_FAILED(400001, "Tạo tài khoản không thành công"),
    USERNAME_INVALID(400002, "Tài khoản hoặc mật khẩu không đúng"),
    DUPLICATE_USERNAME(400003, "Tên tài khoản đã tồn tại. Vui lòng thử lại."),
    USERNAME_IS_NOT_BLANK(400004, "Tên tài khoản không được để trống"),
    PASSWORD_IS_NOT_BLANK(400005, "Mật khẩu không được để trống"),
    USER_NOT_FOUND(400006, "Người dùng không tồn tại"),
    OLD_PWD_INVALID(400007, "Mật khẩu cũ không đúng"),
    CONFIRMPASSWORD_IS_NOTMATCH_PASSWORD(400008,"Mật khẩu mới và xác nhận mật khẩu mới phải trùng nhau "),
    PASSWORD_FORMAT_INVALID(400009,"Mật khẩu có độ dài từ 8 đến 20 ký tự"),
    IS_STRONG_PASSWORD(400010,"Mật khẩu chưa đủ mạnh."),
    //CHANGE_PASSWORD_IS_NOT_SUCCESS(400011,"Đổi mật khẩu thất bại"),
    //IS_EMPTY(400012,"Tên tài khoản, mật khẩu hoặc xác nhận mật khẩu không được trống"),
    DUPLICATE_OLD_PASS_AND_CONFIRM_PASS(400013,"Mật khẩu mới không được trùng mật khẩu cũ."),
    KEYWORD_SEARCH_IS_EMPTY(400014,"Từ khóa tìm kếm không được trống"),
    LIST_MEMBER_IS_NULL(400015,"Danh sách tìm kiếm rỗng"),
    MEMBER_IS_NOT_EXIST(400016,"Hội viên không tồn tại"),
    UPDATE_MEMBER_STATUS_SUCCESSFULLY(400017,"Cập nhật thành công"),
    UPDATE_MEMBER_STATUS_FAILED(400018,"Cập nhật thất bại"),
    DELETE_MEMBER_SUCCESS(400019,"Xoá thành công"),
    DELETE_MEMBER_FAILED(400020,"Xóa thất bại"),
    PHONE_DUPILICATE(400021,"Số điện thoại đăng kí không được trùng nhau"),
    DUPLICATE_LEVEL_ORGANIZATION_NAME(400022, "Cấp tổ chức đã tồn tại. Vui lòng thử lại."),
    DUPLICATE_LEVEL_ORGANIZATION(400023, "Chỉ được phép tạo các Cấp tổ chức trùng cấp từ cấp 4 trở lên"),
    DUPLICATE_LEVEL_ORGANIZATION_NOT_FOUND(400024, "Cấp tổ chức không tồn tại."),
    DUPLICATE_BLOCK_ORGANIZATION_NAME(400025, "Tên Khối tổ chức đã tồn tại. Vui lòng thử lại."),
    DUPLICATE_BLOCK_ORGANIZATION_NOT_FOUND(400026, "Khối tổ chức không tồn tại."),
    BLOCK_ORGANIZATION_NAME_IS_NULL(400027, "Tên khối tổ chức không được để trống."),
    LEVEL_ORGANIZATION_NAME_IS_NULL(400028, "Tên cấp tổ chức không được để trống."),
    LEVEL_ORGANIZATION_IS_NULL(400029, "Cấp tổ chức không được để trống."),
    FIELD_NAME_IS_NOT_BLANK(400030, "{} không được để trống"),
    FIELD_NAME_EXISTED(400031, "{} đã tồn tại. Vui lòng thử lại"),
    FIELD_NAME_MUST_CHOOSE(400032, "Vui lòng chọn {}"),
    FIELD_NAME_INVALID(400033, "{} không đúng định dạng"),
    REASON_REJECT_IS_NULL(400034,"Lý do từ chối không được để trống"),
    PHONE_IS_EXIST(400035,"SĐT đã đăng ký tài khoản trên hệ sinh thái chính trị xã hội, vui lòng nhập SĐT khác!"),
    PHONE_FORMAT_IS_WRONG(400036,"SĐT không hợp lệ. Vui lòng nhập lại!"),
    REGISTER_MEMBER_FAILED(400037,"Khai báo thông tin hội viên lên hệ thống thất bại"),
    APPROVE_MEMBER_SUCCESS(400038,"Phê duyệt hội viên thành công!"),
    OBJECT_NOT_FOUND(400039, "{} không tồn tại"),
    ORG_PARENT_NULL(400040, "Tổ chức cha không được để trống."),
    ORG_NAME_NULL(400041, "Tổ chức không được để trống."),
    ORG_LEVEL_ORGANIZATION_NULL(400042, "Cấp tổ chức không được để trống."),
    ORG_BLOCK_ORGANIZATION_NULL(400043, "Khối tổ chức không được để trống."),
    ORG_DUPLICATE_NAME(400044, "Tên tổ chức đã tồn tại. Vui lòng thử lại."),
    COMPARE_LEVEL_ORGANIZATION(400045, "Cấp tổ chức không thấp hơn Cấp của Tổ chức cha"),
    COMPARE_FIX_ORGANIZATION(400046, "Không cho đổi tên tổ chức Hội nông dân 63 tỉnh thành"),
    ORG_NOT_FOUND(400046, "Tổ chức không tồn tại."),
    ORG_DELETE_SUCCESS(0, "Xóa tổ chức thành công."),
    ORG_LEVEL_DELETE_SUCCESS(0, "Xóa cấp tổ chức thành công."),
    ORG_BLOCK_DELETE_SUCCESS(0, "Xóa khối tổ chức thành công."),
    ORG_BLOCK_DELETE_FAILED_CONSTRAINT(400050, "Không thể xóa khối tổ chức vì ràng buộc dữ liệu."),
    ORG_LEVEL_DELETE_FAILED_CONSTRAINT(400051, "Không thể xóa cấp tổ chức vì ràng buộc dữ liệu."),
    ORG_DELETE_FAILED_CONSTRAINT(400052, "Không thể xóa tổ chức vì ràng buộc dữ liệu."),
    ORG_DELETE_NOT_FOUND(400053, "Tổ chức bạn chọn không tồn tại."),
    ORG_LEVEL_DELETE_NOT_FOUND(400054, "Cấp tổ chức bạn chọn không tồn tại."),
    ORG_BLOCK_DELETE_NOT_FOUND(400055, "Khối tổ chức bạn chọn không tồn tại."),
    REJECT_MEMBER_FAILED(400056,"Lỗi yêu cầu phê duyệt hội viên của bạn không thành công"),
    APPROVE_MEMBER_FAILED(400057,"Từ chối hội viên thành công!"),
    ACTIVE_MEMBER_FAILED(400058,"Hội viên đã bị tạm dừng hoạt động!"),
    PENDING_MEMBER_FAILED(400059,"Lỗi tài khoản của bạn chưa thể tạm dừng tư cách hội viên"),
    ACTIVE_MEMBER_SUCCESS(400060,"Kích hoạt hội viên thành công!"),
    PENDING_MEMBER_SUCCESS(400061,"Lỗi tài khoản của bạn chưa thể kích hoạt lại tư cách hội viên"),

    CITIZENID_IS_WRONG_FORMAT(400062,"Số CMND/CCCD không hợp lệ, vui lòng kiểm tra lại"),
    DATE_OF_BIRTHCANNOT_LARGE_THAN_CURRENT_TIME(400063,"Ngày sinh không được vượt quá ngày hiện tại"),
    PERIOD_BETWEEN_DOB_AND_DATE_OF_ISSUE(400064,"Ngày cấp CCCD/CMND không nhỏ hơn ngày sinh"),
    PLACE_OF_ISSUE_CAN_NOT_EMPTY(400065,"Nơi cấp không được để trống"),
    CHANGE_CITIZEN_ID_DONT_CHANGE(400066,"Không được thay đổi mã CCCD"),
    TYPE_CITIZENID_IS_NOT_EXIST(400067,"Loại CCCD/CMND không tồn tại"),

    REGISTER_MEMBER_SUCCESS(400068,"Thêm mới hội viên thành công"),
    CITY_IS_NOT_EXIST(400069,"Thành phố không tồn tại"),
    DISTRIC_IS_NOT_EXIST(400070,"Quận/Huyện không tồn tại"),
    WARD_IS_NOT_EXIST(400071,"Xã/Phường không tồn tại"),
    DATE_OF_BIRTH_IS_NOT_CORRECT(400072,"Ngày sinh không đúng"),
    DATE_OF_ISSUE_IS_NOT_CORRECT(400073,"Ngày cấp CCCD/CMND không đúng"),
    CREATE_ACCOUNT_FOR_EXIST_USER_FAILED(400074,"Tạo account cho hội viên không thành công"),
    FULL_NAME_IS_NOT_BLANK(400075, "Họ tên không được để trống"),
    EMAIL_IS_NOT_BLANK(400076, "Email không được để trống"),
    EMAIL_INVALID(400077, "Địa chỉ email không hợp lệ"),
    ORG_LIST_MUST_CHOOSE(400078, "Vui lòng chọn khu vực quản lý"),
    GROUP_NAME_NOT_BLANK(400079, "Tên nhóm quyền không được để trống"),
    GROUP_NAME_EXISTED(400080, "Tên nhóm quyền đã tồn tại. Vui lòng thử lại"),
    LIST_PERMISSION_MUST_CHOOSE(400081, "Vui lòng chọn danh sách quyền"),
    GROUP_NOT_FOUND(400082, "Nhóm quyền không tồn tại"),
    PHONE_CAN_NOT_EMPTY(400083,"Số điện thoại không được để trống"),
    CITIZENID_CAN_NOT_EMPTY(400084," Số CMND/CCCD không được để trống"),
    MEMBER_IS_STILL_PENDING(400085,"Hội viên đang trong danh sách chờ duyệt"),
    USERNAME_CANT_DUPLICATE(400086,"Tài khoản đã bị trùng"),
    GROUP_ID_IS_NOT_BLANK(400087,"Nhóm quyền không được để trống"),
    MEMBER_NOT_ASYN_ID(400088, "Account chưa được đồng bộ"),

    CANT_LOCK_YOURSELF(400088, "Không thể khoá chính mình"),
    CANT_DELETE_YOURSELF(400089, "Không thể xoá chính mình"),

    MEMBER_WAS_DELETED(400090,"Người dùng đã bị không còn tư cách hội viên"),

    EMAIL_WRONG_FORMAT(400091, "Địa chỉ email không hợp lệ"),
    DISTRICT_CAN_NOT_EMPTY(400092,"Quận/Huyện không được để trống"),
    WARD_CAN_NOT_EMPTY(400093,"Phường/Xã không được để trống"),

    NAME_OVER_LENGTH(400094,"Đã đạt kí tự giới hạn cho phép"),
    LEVEL_ORGANIZATION_ADDED(0, "Thêm mới thành công"),
    LEVEL_ORGANIZATION_UPDATED(0, "Cập nhật thành công"),
    BLOCK_ORGANIZATION_ADDED(0, "Thêm mới thành công"),
    BLOCK_ORGANIZATION_UPDATED(0, "Cập nhật thành công"),
    ORGANIZATION_ADDED(0, "Thêm mới thành công"),
    ORGANIZATION_UPDATED(0, "Cập nhật thành công"),

    IS_POSITIVE_NUMBER(400095,"Chỉ nhập số nguyên dương"),
    FIELD_NAME_LEVEL_ORGANIZATION_INVALID(400033, "Chỉ nhập số"),
    LIST_KHOI_ID_CAN_NOT_EMPTY(400096,"Danh sách khối không được để trống"),
    LIST_ORG_ID_CAN_NOT_EMPTY(400097,"Danh sách tổ chức không được để trống"),
    GROUP_NAME_TOO_LONG(400098, "Tên nhóm quyền quá dài"),
    USERNAME_TOO_LONG(400099, "Tên đăng nhập quá dài"),
    FULL_NAME_TOO_LONG(400099, "Họ tên quá dài"),
    EMAIL_TOO_LONG(400099, "Email quá dài"),

    //File
    FILE_NOT_EMPTY_DEFAULT(4000100,"File không được để trống"),
    FILE_TOO_LARGE_EVENT_DEFAULT(4000101,"File vướt quá 1MB, vui lòng chọn lại"),
    FILE_INVALID_EVENT_DEFAULT(4000102,"File không đúng định dạng, vui lòng chọn lại."),
    FILE_TOO_LARGE_DELEGATION(4000103,"File vướt quá 5MB, vui lòng chọn lại."),
    FILE_INVALID_DELEGATION(4000104,"Nội dung import không đúng định dạng file mẫu"),
    FILE_EMPTY_DELEGATION(4000105,"Thông tin trên file import rỗng"),
    FILE_INVALID_IMAGE_VOTE(4000106,"Ảnh tải lên phải có định dạng jpg, png"),
    FILE_TOO_LARGE_IMAGE_VOTE(4000107,"Ảnh tải lên có dung lượng không vượt quá 10MB"),


    //congressInfo
    CONGRESS_NOT_FOUND(4000207, "Không tìm thấy thông tin đại hội."),
    CONGRESS_NAME_NOT_BLANK(4000208, "Tên Đại hội không được để trống."),
    CONGRESS_NAME_INVALID(4000209, "Tên Đại hội không được quá 60 ký tự."),
    CONGRESS_STATUS_INVALID(4000210, "Trạng thái Đại hội không hợp lệ."),
    CONGRESS_CREATE_SUCCESSFUL(0, "Tạo mới thành công."),
    CONGRESS_UPDATE_SUCCESSFUL(0, "Cập nhật thành công."),
    //delegation
    DELEGATE_NOT_FOUND(4000210, "Không tìm thấy thông tin đại biểu."),
    DELEGATE_NAME_NOT_BLANK(4000211, "Tên đại biểu không được để trống."),
    DELEGATE_NAME_INVALID(4000212, "Tên đại biểu không được quá 60 ký tự."),
    DELEGATE_CITIZEN_ID_NOT_BLANK(4000213, "Số CCCD/CMT không được để trống."),
    DELEGATE_CITIZEN_ID_INVALID(4000214, "Số CCCD/CMT không đúng định dạng."),
    DELEGATE_UNION_ID_INVALID(4000215, "ID Đoàn đại biểu không hợp lệ."),
    DELEGATE_PHONE_NUMBER_INVALID(4000216, "Số điện thoại không đúng định dạng."),
    DELEGATE_CREATE_SUCCESSFUL(0, "Thêm mới thành công."),
    DELEGATE_UPDATE_SUCCESSFUL(0, "Cập nhật thành công."),
    DELEGATION_CITIZEN_ID_EXISTED(4000250, "Số CCCD/CMT đã tồn tại. Vui lòng thử lại."),
    DELEGATION_CITIZEN_ID_NOT_MATCH(4000251, "Tên đại biểu và tên hội viên khai báo cho số CCCD/CMT này không giống nhau"),
    DELEGATION_PHONE_NUMBER_EXISTED(4000252, "Số điện thoại đã tồn tại."),
    DELEGATION_PHONE_NUMBER_IS_REQUIRE(4000253, "Thiếu thông tin số điện thoại."),
    DELEGATION_UNION_NAME_IS_REQUIRE(4000253, "Thiếu thông tin đoàn đại biểu ."),
    DELEGATION_CITIZEN_ID_IS_REQUIRE(4000253, "Thiếu thông tin căn cước công dân."),
    DELEGATION_NAME_IS_REQUIRE(4000253, "Thiếu thông tin tên Đại biểu."),
    DELEGATION_POSITION_IS_REQUIRE(4000253, "Thiếu thông tin chức vụ."),
    DELEGATION_WORK_PLACE_IS_REQUIRE(4000253, "Thiếu thông tin nơi công tác."),
    DELEGATION_STT_IS_REQUIRE(4000253, "Thiếu thông tin số thứ tự."),
    DELEGATION_AVATAR_IS_REQUIRE(4000253, "Thiếu thông tin ảnh đại diện."),
    DELEGATION_EXISTED(4000254, "Đại biểu đã tồn tại."),
    DELEGATION_UNION_NAME_NOT_FOUND(4000256, "Thông tin Đoàn đại biểu không tồn tại trên hệ thống."),
    DELEGATION_FILE_UPLOAD_EXIT_INVALID_ELEMENT(4000257, "File upload Đoàn đại biểu tồn tại dòng không hợp lệ."),
    DELEGATION_FILE_UPLOAD_INVALID_FORMAT(4000258, "Nội dung import không đúng định dạng file mẫu."),
    DELEGATION_FILE_UPLOAD_EMPTY(4000259, "Thông tin trên file import rỗng."),
    DELEGATION_INSERT_ALL_SUCCESS(0, "Thêm danh sách Đại biểu thành công."),
    DELEGATION_POSITION_INVALID(4000260, "Chức vụ không được quá 200 ký tự."),
    DELEGATION_WORK_PLACE_INVALID(4000261, "Nơi công tác không được quá 200 ký tự."),

    //DELEGATION_UNION
    CREATE_SUCCESS(0,"Thêm mới thành công"),
    DELEGATION_UNION_NAME_ALREADY_EXISTS(4000217, "Tên đoàn đại biểu đã tồn tại. Vui lòng thử lại."),
    DELEGATION_UNION_NAME_NULL(4000218, "Tên đoàn đại biểu không được để trống."),
    DELEGATION_UNION_NAME_OVER_LIMIT(4000219, "Tên đoàn đại biểu không được vượt quá 60 ký tự."),
    DELEGATION_UNION_ORD_FORMAT_WRONG(4000220, "Thứ tự đoàn đại biểu không đúng format"),
    UPDATE_SUCCESS(0,"Cập nhật thành công"),
    DELEGATION_UNION_NOT_FOUND(4000221, "Đoàn đại biểu không tồn tại."),
    DELEGATION_UNION_CONSTRAIN_KEY(4000222, "Không thể xóa đoàn đại biểu vì ràng buộc dữ liệu"),
    DELETE_DELEGATION_SUCCESS(0, "Xóa đoàn đại biểu thành công "),
    //Event
    EVENT_EMPTY_NAME(4000300, "Tên phiên không được để trống"),
    EVENT_INVALID_TIME(4000301, "Thời gian bắt đầu phải nhỏ hơn thời gian kết thúc"),
    CATE_NOT_FOUND(4000302, "Id không tồn tại"),
    CATE_CONSTRAIN_EXISTS(4000303, "Không thể xóa vì ràng buộc dữ liệu"),
    DELETE_CATE_SUCCESS(0, "Xóa thành công"),
    ID_CATE_INVALID(4000304, "Id không hợp lệ"),
    CATE_INVALID(4000305, "{} không hợp lệ"),
    SESSION_EMPTY_NAME(4000306, "Tên phiên không được để trống"),
    SESSION_INVALID_TIME(4000307, "Thời gian bắt đầu phải nhỏ hơn hoặc bằng thời gian kết thúc"),
    SESSION_EMPTY_TIME_CHECKIN(4000308, "Hiệu lực mã checkin không được bỏ trống"),
    SESSION_ADD_SUCCESS(0, "Thêm mới thành công"),
    SESSION_UPDATE_SUCCESS(0, "Cập nhật thành công"),
    SESSION_START_CHECKIN(0, "Đã bắt đầu check-in"),
    SESSION_END_CHECKIN(0, "Đã dừng check-in"),
    SESSION_DELETE_NOT_EXIST(4000311, "Phiên đại hội không tồn tại."),
    INVALID_JOIN_DATE(4000309,"Ngày vào hội không đúng định dạng"),
    INVALID_JOIN_DATE_NOT_ALLOWED(4000310,"Chỉ cho phép chọn đến ngày hiện tại"),
    SESSION_CANT_DELETE_BC_OF_DATA_BINDING(400311,"Không thể xóa dữ liệu vì ràng buộc dữ liệu"),

    //voting
    ORD_VOTING_TYPE_MAX(400312, "Không thể vượt quá giới hạn thứ tự hiển thị"),
    VOTING_IS_WORKING(0, "Biểu quyết đã bắt đầu"),
    VOTING_IS_FINISH(0,"Đã dừng biểu quyết"),
    RANGE_CHARACTER_VOTING_NAME(410000, "Tên biểu quyết không được vượt quá 60 ký tự"),
    TIME_VOTING_MUST_BE_LONGER_THAN_CURRENT_TIME(410001, "{} phải lớn hơn thời gian hiện tại"),
    CONDITION_TIME_START_AND_TIME_END(410002,"Giá trị từ ngày phải nhỏ hơn hoặc bằng giá trị Đến ngày"),
    ORD_VOTING_TYPE(410003,"Thứ tự hiển thị phải là số nguyên dương"),
    ID_VOTING_CANT_EMPTY(410004, "Mã biểu quyết không được để trống"),
    VOTING_FINISHED(410005,"Biểu quyết đã kết thúc"),
    VOTING_Q_CANNOT_FIND(410006,"Nội dung biểu quyết không tồn tại"),
    MEMBER_VOTED(410007,"Hội viên đã tham gia biểu quyết trước đó. Không thể biểu quyết"),
    VOTING_NOT_FOUND(410008, "Biểu quyết không tồn tại"),
    MEMBER_DONT_HAVE_ROLE(410009, "Bạn không phải là hội viên. Không có quyền truy cập vào đây"),
    TIME_SEESION_END(410010, "Phiên đại hội đã kết thúc. Vui lòng chọn phiên đại hội khác."),
    TIME_SESSION_START_EARLY(410011, "Thời gian bắt đầu phiên đại hội này chưa đến. Vui lòng chọn phiên đại hội khác"),
    CHECKIN_LOG_SUCCESS(0, "Check-in thành công"),
    CHECKIN_LOG_EXIST(1, "Đã từng Check-in"),
    CHECKIN_LOG_EXPIRE(400501, "Mã QR không hợp lệ"),
    CHECKIN_LOG_NOT_START(400502, "Mã QR không hợp lệ"),
    CHECKIN_LOG_FAIL(400002, "Mã QR không hợp lệ"),
    UPDATE_DELEGATION_UNION_SUCCESS(0,"Cập nhật Đoàn đại biểu thành công"),
    //app
    USER_PROFILE_IS_NOT_EXIST(-1,"Người dùng không tồn tại"),
    MEMBER_CANNOT_DECLARE_INFO_APP(410012,"Hội viên không thể khai báo"),
    MEMBER_DOESNOT_HAVE_ROLE(410013, "Bạn không có quyền quản lý hội viên"),
    MEMBER_DELETE_SUCCESS(0, "Xóa hội viên thành công"),
    UPDATE_DELEGATION_UNION(410014,"Cập nhật Đoàn đại biểu thành công"),
    UPDATE_DELEGATION_UNION_FAILED(410015,"Cập nhật Đoàn đại biểu không thành công"),
    UPLOAD_DELEGATION_UNION_WRONG_FORMAT(410016,"Nội dung import không đúng định dạng file mẫu"),
    UPLOAD_DELEGATION_UNION_OVER_LIMIT_SIZE(410017,"File vượt quá 5MB, vui lòng chọn lại."),
    FILE_UPLOAD_EMPTY(410018, "File không được trống"),
    FILE_UPLOAD_WRONG_EXTENSIONS(410019, "File không đúng định dạng, vui lòng chọn lại."),
    FILE_UPLOAD_DATA_EMPTY(410020, "Thông tin trên file import rỗng."),
    QUESTION_VOTING_NOT_EXIST(420000,"Câu hỏi không tồn tại"),
    ANSWER_QUESTION_NOT_EXIST(420001, "Câu trả lời không tồn tại"),
    MEMBER_ORG_DONT_HAVE_ROLE(420002,"Chức năng này chỉ dành cho tổ chức trên cấp xã"),


    NOT_FOUND_DATA(42004, "Không tìm thấy dữ liệu"),
    LEVEL_ORG_MUST_LT_LEVEL_GRP_PERMISSION(42003,"Cấp tổ chức đã chọn không phù hợp với cấp tổ chức của " +
            "nhóm quyền"),
    //hoi vien tren app
    CAN_NOT_APPROVE_MEMBER(490000, "Không thể duyệt hội viên"),
    MEMBER_ARE_NOT_DELEGATION(490001,"Bạn không phải là đại biểu"),
    MEMBER_IS_PENDING(490002, "Hội viên bị tạm dừng không thể gán quyền"),
    //hoi vien tren portal

    ACCOUNT_MEMBER_CAN_NOT_EMPTY(490003, "SĐT hoặc email không được để trống"),
    EMAIL_ACCOUNT_EXIST(490004, "Tài khoản đã tồn tại. Vui lòng sử dụng email đã đăng ký để đăng nhập!"),
    ACCOUNT_DUPILICATE(490005,"Tài khoản đã tồn tại"),

    APP_MEMBER_APPROVE_SUCCESS(0, "Hội viên được duyệt thành công!"),
    APP_MEMBER_LIST_APPROVE_SUCCESS(0, "Các hội viên được duyệt thành công!"),
    APP_MEMBER_DECLINE_SUCCESS(0, "Hội viên đã bị từ chối duyệt!"),
    APP_MEMBER_DECLINE_LIST_SUCCESS(0, "Các hội viên đã bị từ chối duyệt!"),
    APP_MEMBER_DELETE_LIST_SUCCESS(0, "Các hội viên đã xóa thành công! "),
    APP_MEMBER_PENDING_SUCCESS(0, "Hội viên đã bị tạm dừng!"),
    APP_MEMBER_ACTIVE_SUCCESS(0, "Hội viên đã được kích hoạt!"),
    APP_MEMBER_ASSIGN_SUCCESS(0, "Hội viên được gán quyền duyệt thành công!"),
    APP_MEMBER_UN_ASSIGN_SUCCESS(0, "Hội viên đã bị gỡ quyền duyệt!"),
    APP_MEMBER_DELETE_SUCCESS(0, "Hội viên đã bị xoá!"),
    APP_MEMBER_DELETE_FAIL(-1, "Xóa hội viên thất bại!"),
    UPDATE_MEMBER_INFO_APP(0,"Cập nhật thông tin thành công"),

    CHANNEL_NAME_SIZE(400099,"Tên Kênh Thông Báo không được vượt quá 100 ký tự"),
    ADMIN_CHANNEL_SIZE(400100, "Số lượng quản trị viên tối đa không vượt quá 5 người"),
    CHANNEL_ORG_EXIST(400101,"Kênh thông báo của tổ chức đã tồn tại"),
    MEMBER_IS_ADMIN_CHANNEL_IN_ORG(400102, "Đoàn viên đã là quản trị viên kênh thông báo tại tổ chức này"),
    MEMBER_IS_NOT_EXIST_IN_ORG(400108, "Đoàn viên không thuộc tổ chức"),

    CREATE_CHANNEL_SUCCESSFUL(400103,"Tạo kênh thông báo thành công"),
    CREATE_CHANNEL_FAILED(400104,"Tạo kênh thông báo thất bại"),
    UPDATE_CHANNEL_SUCCESSFUL(400105, "Cập nhật kênh thông báo thành công"),
    UPDATE_CHANNEL_FAILED(400106,"Cập nhật kênh thông báo thất bại"),
    CHANNEL_ORG_NOT_EXIST(400107, "Kênh thông báo của tổ chức không tồn tại"),
    CHANNEL_ORG_CREATE_SUCCESS(0, "Kênh thông báo được tạo thành công"),

    CHANNEL_ORG_INACTIVE_SUCCESS(0, "Kênh thông báo được ẩn thành công"),

    CHANNEL_ORG_ACTIVE_SUCCESS(0, "Kênh thông báo được hiện thành công"),
    TYPE_CITIZEN_INVALID(400107, "Type citizen chỉ có thể là 1 hoặc 2"),
    DOWNLOAD_REPORT_FILE_SUCCESS(0, "Tải báo cáo thành công!"),
    DOWNLOAD_REPORT_FILE_FAIL(-1, "Tải báo cáo thất bại!"),
    FILE_DELEGATION_UPLOAD_TOO_LARGE(4000103,"File vướt quá 60MB, vui lòng chọn lại."),
    ;

    public int code;
    public String message;

    CommonMessage(int code, String message) {
        this.code = code;
        this.message = message;
    }

    CommonMessage(int code) {
        this.code = code;
    }
}
